name = 'itch-ttrpg-discovery-email'
main = "email.js"
compatibility_date = "2026-07-10"

[triggers]
crons = ["0 12 1 * *"]

[[d1_databases]]
binding = "DB"
database_name = "itch-rpg-feed"
migrations_dir = "../migrations"
database_id = "9c508136-520e-4731-aba3-321d40cc13c6"


[observability.logs]
enabled = true
invocation_logs = true
